# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import success_rate_pb2 as success__rate__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in success_rate_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SuccessRateCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchSuccessRate = channel.unary_unary(
                '/success_rate.SuccessRateCalculator/FetchSuccessRate',
                request_serializer=success__rate__pb2.CalSuccessRateRequest.SerializeToString,
                response_deserializer=success__rate__pb2.CalSuccessRateResponse.FromString,
                _registered_method=True)
        self.UpdateSuccessRateWindow = channel.unary_unary(
                '/success_rate.SuccessRateCalculator/UpdateSuccessRateWindow',
                request_serializer=success__rate__pb2.UpdateSuccessRateWindowRequest.SerializeToString,
                response_deserializer=success__rate__pb2.UpdateSuccessRateWindowResponse.FromString,
                _registered_method=True)
        self.InvalidateWindows = channel.unary_unary(
                '/success_rate.SuccessRateCalculator/InvalidateWindows',
                request_serializer=success__rate__pb2.InvalidateWindowsRequest.SerializeToString,
                response_deserializer=success__rate__pb2.InvalidateWindowsResponse.FromString,
                _registered_method=True)
        self.FetchEntityAndGlobalSuccessRate = channel.unary_unary(
                '/success_rate.SuccessRateCalculator/FetchEntityAndGlobalSuccessRate',
                request_serializer=success__rate__pb2.CalGlobalSuccessRateRequest.SerializeToString,
                response_deserializer=success__rate__pb2.CalGlobalSuccessRateResponse.FromString,
                _registered_method=True)


class SuccessRateCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchSuccessRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSuccessRateWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateWindows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchEntityAndGlobalSuccessRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuccessRateCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchSuccessRate': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchSuccessRate,
                    request_deserializer=success__rate__pb2.CalSuccessRateRequest.FromString,
                    response_serializer=success__rate__pb2.CalSuccessRateResponse.SerializeToString,
            ),
            'UpdateSuccessRateWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSuccessRateWindow,
                    request_deserializer=success__rate__pb2.UpdateSuccessRateWindowRequest.FromString,
                    response_serializer=success__rate__pb2.UpdateSuccessRateWindowResponse.SerializeToString,
            ),
            'InvalidateWindows': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateWindows,
                    request_deserializer=success__rate__pb2.InvalidateWindowsRequest.FromString,
                    response_serializer=success__rate__pb2.InvalidateWindowsResponse.SerializeToString,
            ),
            'FetchEntityAndGlobalSuccessRate': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchEntityAndGlobalSuccessRate,
                    request_deserializer=success__rate__pb2.CalGlobalSuccessRateRequest.FromString,
                    response_serializer=success__rate__pb2.CalGlobalSuccessRateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'success_rate.SuccessRateCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('success_rate.SuccessRateCalculator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuccessRateCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchSuccessRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/success_rate.SuccessRateCalculator/FetchSuccessRate',
            success__rate__pb2.CalSuccessRateRequest.SerializeToString,
            success__rate__pb2.CalSuccessRateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSuccessRateWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/success_rate.SuccessRateCalculator/UpdateSuccessRateWindow',
            success__rate__pb2.UpdateSuccessRateWindowRequest.SerializeToString,
            success__rate__pb2.UpdateSuccessRateWindowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateWindows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/success_rate.SuccessRateCalculator/InvalidateWindows',
            success__rate__pb2.InvalidateWindowsRequest.SerializeToString,
            success__rate__pb2.InvalidateWindowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchEntityAndGlobalSuccessRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/success_rate.SuccessRateCalculator/FetchEntityAndGlobalSuccessRate',
            success__rate__pb2.CalGlobalSuccessRateRequest.SerializeToString,
            success__rate__pb2.CalGlobalSuccessRateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
